[package]
name = "weather-app-rust"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.0.0"
jsonwebtoken = "8.0.0"
serde = { version = "1.0", features = ["derive"]}
serde_json = "1.0"
bcrypt ="0.10"
tokio = {version = "1", features = ["full"]}
